Repository archtechx/tenancy, pull requests merged in 2022-07, with the labels that each got.

#904 Removed unused variable `PHP_CS_FIXER_IGNORE_ENV` from CI.
  .github/workflows/ci.yml
Labels: code quality

#679 feat(UniversalRoutes): Stop overwriting the (maybe) customized onFail…
  src/Features/UniversalRoutes.php
  tests/DomainTest.php
Labels: v4, routing

#907 Put $mockConsoleOutput property back
  tests/BootstrapperTest.php
  tests/QueueTest.php
Labels: v4
