Repository archtechx/tenancy, pull requests merged in 2022-09, with the labels that each got.

#923 [4.x] Improve `tenants:run` command to execute Input\Output commands
  src/Commands/Run.php
  tests/CommandsTest.php
  tests/Etc/Console/AddUserCommand.php
  tests/Etc/Console/ConsoleKernel.php
  tests/Etc/Console/ExampleCommand.php
  tests/Etc/Console/ExampleQuestionCommand.php
  tests/TestCase.php
Labels: v4

#925 [4.x] Set tenant as a default parameter for the URLs when using Path identification
  src/Middleware/InitializeTenancyByPath.php
  tests/PathIdentificationTest.php
Labels: v4, routing, ready

#938 [4.x] Optionally delete storage after tenant deletion
  assets/TenancyServiceProvider.stub.php
  src/Listeners/DeleteTenantStorage.php
  tests/BootstrapperTest.php
Labels: feature, v4

#947 [4.x] Finish incomplete and missing tests
  src/Database/TenantDatabaseManagers/SQLiteDatabaseManager.php
  tests/CommandsTest.php
  tests/SingleDatabaseTenancyTest.php
  tests/TenantDatabaseManagerTest.php
Labels: v4

#874 [4.x] Add batch tenancy queue bootstrapper
  assets/config.php
  src/Bootstrappers/BatchTenancyBootstrapper.php
  tests/BatchTest.php
  tests/TestCase.php
Labels: Don't merge yet, v4

#909 [4.x] Storage::url() support (modified #689)
  assets/TenancyServiceProvider.stub.php
  assets/config.php
  src/Actions/CreateStorageSymlinksAction.php
  src/Actions/RemoveStorageSymlinksAction.php
  src/Bootstrappers/FilesystemTenancyBootstrapper.php
  src/Commands/Link.php
  src/Concerns/DealsWithTenantSymlinks.php
  src/Events/CreatingStorageSymlink.php
  src/Events/RemovingStorageSymlink.php
  src/Events/StorageSymlinkCreated.php
  src/Events/StorageSymlinkRemoved.php
  src/Jobs/CreateStorageSymlinks.php
  src/Jobs/RemoveStorageSymlinks.php
  src/TenancyServiceProvider.php
  tests/ActionTest.php
  tests/BootstrapperTest.php
  tests/CommandsTest.php
  tests/SingleDatabaseTenancyTest.php
Labels: feature, v4, final review
